export const ROUTES_METADATA = Symbol('ROUTES_METADATA');
export const PARAM_METADATA = Symbol('PARAM_METADATA');
export const GUARDS_METADATA = Symbol('GUARDS_METADATA');
export const MIDDLEWARES_METADATA = Symbol('MIDDLEWARES_METADATA');
export const INTERCEPTOR_METADATA = Symbol('INTERCEPTOR_METADATA');
export const CONTROLLER_METADATA = Symbol('CONTROLLER_METADATA');
export const STATUS_CODE_METADATA = Symbol('STATUS_CODE_METADATA');

export const APP_TOKEN = Symbol('EXPRESSX_APP');
export const GLOBAL_EXCEPTION_HANDLER = Symbol('EXPRESSX_GLOBAL_EXCEPTION_HANDLER');
